# Project Name
TARGET = Senior-Design-Project-1

# Use DaisySP
USE_DAISYSP_LGPL=1

# Source files
CPP_SOURCES = \
    Senior-Design-Project-1.cpp \
    ../../libDaisy/src/hid/analog_switch.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy/
DAISYSP_DIR = ../../DaisySP/

# Core location and include the generic Makefile
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

